# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1047, 674)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 50, 1026, 578))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_evaluate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_evaluate.setGeometry(QtCore.QRect(12, 630, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.pushButton_evaluate.setFont(font)
        self.pushButton_evaluate.setObjectName("pushButton_evaluate")
        self.pushButton_answer = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_answer.setGeometry(QtCore.QRect(172, 630, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.pushButton_answer.setFont(font)
        self.pushButton_answer.setObjectName("pushButton_answer")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 10, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_reset = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_reset.setGeometry(QtCore.QRect(712, 630, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.pushButton_reset.setFont(font)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(872, 630, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_next = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_next.setGeometry(QtCore.QRect(362, 630, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.pushButton_next.setFont(font)
        self.pushButton_next.setObjectName("pushButton_next")
        self.pushButton_last = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_last.setGeometry(QtCore.QRect(522, 630, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.pushButton_last.setFont(font)
        self.pushButton_last.setObjectName("pushButton_last")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_evaluate.clicked.connect(MainWindow.evaluate) # type: ignore
        self.pushButton_answer.clicked.connect(MainWindow.answer) # type: ignore
        self.pushButton_reset.clicked.connect(MainWindow.reset) # type: ignore
        self.pushButton.clicked.connect(MainWindow.helpinfo) # type: ignore
        self.pushButton_next.clicked.connect(MainWindow.next) # type: ignore
        self.pushButton_last.clicked.connect(MainWindow.last) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stock Chart Viewing Training System"))
        self.pushButton_evaluate.setText(_translate("MainWindow", "Evaluate"))
        self.pushButton_answer.setText(_translate("MainWindow", "Answer"))
        self.label.setText(_translate("MainWindow", "Your Attention Map (0)"))
        self.pushButton_reset.setText(_translate("MainWindow", "Reset"))
        self.pushButton.setText(_translate("MainWindow", "Help"))
        self.pushButton_next.setText(_translate("MainWindow", "Next"))
        self.pushButton_last.setText(_translate("MainWindow", "Last"))
