# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1047, 681)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 50, 1026, 578))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_evaluate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_evaluate.setGeometry(QtCore.QRect(180, 630, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.pushButton_evaluate.setFont(font)
        self.pushButton_evaluate.setObjectName("pushButton_evaluate")
        self.pushButton_answer = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_answer.setGeometry(QtCore.QRect(440, 630, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.pushButton_answer.setFont(font)
        self.pushButton_answer.setObjectName("pushButton_answer")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(420, 10, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(700, 630, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_evaluate.clicked.connect(MainWindow.evaluate) # type: ignore
        self.pushButton_answer.clicked.connect(MainWindow.answer) # type: ignore
        self.pushButton.clicked.connect(MainWindow.reset) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stock Chart Viewing Training System"))
        self.pushButton_evaluate.setText(_translate("MainWindow", "Evaluate"))
        self.pushButton_answer.setText(_translate("MainWindow", "Answer"))
        self.label.setText(_translate("MainWindow", "Visual Saliency Map"))
        self.pushButton.setText(_translate("MainWindow", "Reset"))
